version: '3.7'

services:
  db:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD

  gateway:
    depends_on:
      - user
    build:
      context: services/gateway
      args:
        - NODE_ENV=development
    image: federation/services/gateway
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/gateway:/usr/src/app
      - /usr/src/app/node_modules
    command: run start:dev
    ports:
      - 4000:4000

  user:
    depends_on:
      - db
    build:
      context: services/user
      args:
        - NODE_ENV=development
    image: federation/services/user
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/user:/usr/src/app
      - /usr/src/app/node_modules
    command: run start:dev
    ports:
      - 4001:4000
